### ISSUE TITLE
Various code-quality improvements

### ISSUE THREAD

**Issue by Seanny123** [mtien/PeptideBuilder#14]
I would like to submit a pull-request addressing the following:

1. Removing support for Python 2, since it has been unsupported since January
2. Autoformatting the code using [`black`](https://github.com/psf/black)
3. Adding type-annotations for easier interfacing and debugging

However, I before I put in the work, I wanted to make sure these changes were acceptable to the maintainers.

**Comment by clauswilke** [comment]
Thanks for reaching out. Timing is good because I want to release a new version soon and I would have done this already if not for the coronavirus outbreak. I have no concerns about 1, and I assume I'm fine with 3 also though I'd have to see what it means. I'm not usually a big fan of complete code reformatting because it leads to giant diffs that are difficult to review and destroy all project history.

In any case, I'd want to see this broken into three separate PRs, so why don't you start with 1 and 3 first, and we consider 2 after everything else is ready for a release?

**Comment by clauswilke** [comment]
Actually, could you file separate issues for each of the three items, so we can keep track of them one by one?

**Comment by Seanny123** [comment]
Broke this up into multiple issues as requested.
